;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("alphaa" "α" nil :count 0)
    ("betaa" "β" nil :count 0)
    ("chii" "χ" nil :count 0)
    ("commandd" "⌘" nil :count 0)
    ("controll" "⌃" nil :count 0)
    ("deltaa" "δ" nil :count 3)
    ("downn" "↓" nil :count 0)
    ("epsilonn" "ε" nil :count 0)
    ("etaa" "η" nil :count 0)
    ("gammaa" "γ" nil :count 0)
    ("iotaa" "ι" nil :count 0)
    ("kappaa" "κ" nil :count 0)
    ("lambdaa" "λ" nil :count 0)
    ("leftt" "←" nil :count 0)
    ("muu" "μ" nil :count 0)
    ("nuu" "ν" nil :count 0)
    ("omegaa" "ω" nil :count 0)
    ("omicronn" "ο" nil :count 0)
    ("optionn" "⌥" nil :count 0)
    ("phii" "φ" nil :count 0)
    ("pii" "π" nil :count 0)
    ("psii" "ψ" nil :count 0)
    ("rhoo" "ρ" nil :count 0)
    ("rightt" "→" nil :count 0)
    ("shiftt" "⇧" nil :count 0)
    ("sigmaa" "σ" nil :count 0)
    ("tauu" "τ" nil :count 0)
    ("thetaa" "θ" nil :count 0)
    ("upp" "↑" nil :count 0)
    ("upsilonn" "υ" nil :count 0)
    ("xiu" "ξ" nil :count 0)
    ("zetaa" "ζ" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("aaorg" "#+attr_org: :width 600px" nil :count 0)
    ("ppbib" "#+print_bibliography:" nil :count 0)
   ))
